/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package creadordeinsertssql.vista;

import creadordeinsertssql.modelo.Columna;

/**
 *Vista general de una columna. La vista no es editable
 * @author pedruben
 */
public class VistaColumna extends javax.swing.JPanel {

    Columna columna;

    /**
     * Creates new form VistaColumna
     *
     * @param columna
     */
    public VistaColumna(Columna columna) {
        initComponents();
        this.columna = columna;
        this.establecerDatos();
    }

    private void establecerDatos() {
        
       // this.textoTipoDeDato.setText(columna.getTipoDeDato().toString().toUpperCase());
        this.textoClavePrimaria.setText("PK:");
        this.textoClaveExterna.setText("FK:");
        this.textoNull.setText("Nulo:");
        if (this.columna.isPrimaryKey()) {
            visePrimaryKey.setVisible(true);
        } else {
            visePrimaryKey.setVisible(false);
        }
        if (this.columna.isForeignKey()) {
            viseForeignKey.setVisible(true);
        } else {
            viseForeignKey.setVisible(false);
        }
        if (this.columna.isNulo()) {
            viseNull.setVisible(true);
        } else {
            viseNull.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        textoTipoDeDato = new javax.swing.JLabel();
        textoClavePrimaria = new javax.swing.JLabel();
        textoClaveExterna = new javax.swing.JLabel();
        textoNull = new javax.swing.JLabel();
        visePrimaryKey = new javax.swing.JLabel();
        viseForeignKey = new javax.swing.JLabel();
        viseNull = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        setMaximumSize(new java.awt.Dimension(56, 100));
        setName(""); // NOI18N

        textoTipoDeDato.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        textoTipoDeDato.setText("  ");

        textoClavePrimaria.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        textoClavePrimaria.setText("PK:");

        textoClaveExterna.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        textoClaveExterna.setText("FK:");

        textoNull.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        textoNull.setText("Null:");

        visePrimaryKey.setIcon(new javax.swing.ImageIcon(getClass().getResource("/insertsaleatorios/vista/vise.png"))); // NOI18N
        visePrimaryKey.setToolTipText("");

        viseForeignKey.setIcon(new javax.swing.ImageIcon(getClass().getResource("/insertsaleatorios/vista/vise.png"))); // NOI18N

        viseNull.setIcon(new javax.swing.ImageIcon(getClass().getResource("/insertsaleatorios/vista/vise.png"))); // NOI18N
        viseNull.setToolTipText("");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textoClaveExterna, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textoNull)
                            .addComponent(textoClavePrimaria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(viseNull)
                            .addComponent(viseForeignKey)
                            .addComponent(visePrimaryKey))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(textoTipoDeDato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(textoTipoDeDato)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(textoClavePrimaria)
                    .addComponent(visePrimaryKey))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(viseForeignKey)
                    .addComponent(textoClaveExterna))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(viseNull)
                    .addComponent(textoNull))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel textoClaveExterna;
    private javax.swing.JLabel textoClavePrimaria;
    private javax.swing.JLabel textoNull;
    private javax.swing.JLabel textoTipoDeDato;
    private javax.swing.JLabel viseForeignKey;
    private javax.swing.JLabel viseNull;
    private javax.swing.JLabel visePrimaryKey;
    // End of variables declaration//GEN-END:variables
}
